### ISSUE TITLE
Any way to force it to never play HD streams on abc iview and only do SD?

### ISSUE THREAD

**Issue by frumbert** [xbmc-catchuptv-au/plugin.video.abc_iview#3071]
Because australian internet.

**Comment by glennguy** [comment]
Hi @frumbert 
We're currently working on a feature for Kodi 17+ users that would allow adaptive bitrate switching, which would allow you to have the best of both worlds - HD when your internet is being nice, and SD at Netflix o'clock.

In the meantime though, a small 1 line edit is all you would need to remove the HD streams:
In the add-on's lib/resources folder. In parse.py change the line (line 188 in the most up to date code, if not on your copy it will be nearby) from ```p.url = item['playlist'][-1]['hls-plus']``` to ```p.url = item['playlist'][-1]['hls-high']```

@andybotting should we consider a settings option for this, default to on?

**Comment by andybotting** [comment]
@glennguy Yeah, a setting would be ideal, because fraudband :(
