### ISSUE TITLE
Latest version crashes when running

### ISSUE THREAD

**Issue by shavanni** [xbmc-catchuptv-au/plugin.video.abc_iview#3076]
Using SPMC the latest version 1.8.4 crashes when opening the add-on. 
Rolled back to 1.8.2 for it to work again

**Comment by andybotting** [comment]
Can you provide *any* more details than this?

**Comment by andybotting** [comment]
OK, I've replicated it. I'll work on a fix, but this is due to SPMC having an old version of Python bundled. If you could use Kodi v17 this would work.

**Comment by andybotting** [comment]
Fix now committed in the pycaptions module v0.5.6. It is now available in the repository.

Thanks for reporting.

**Comment by shavanni** [comment]
Hi, I've tried updating. Issue still ocurrs

**Comment by andybotting** [comment]
Can you confirm you have pycaptions v0.5.6 installed? The issue is not in the iView add-on

**Comment by shavanni** [comment]
Pycaptions updated today. All good. Thanks

**Comment by andybotting** [comment]
Thanks @shavanni
